name: Deploy Firefox container demo

on:
  workflow_dispatch:
  repository_dispatch:
      types: [deploy_ff_demo]
  pull_request:
    types:
      - closed

jobs:
  setup-infra:
    name: Setup Network Infrastructure
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
      
    defaults:
        run:
          shell: bash
          working-directory: ./

    steps:
      ## Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      ## Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      ## initialize terraform
      - name: Terraform Init
        id: init
        run: terraform init -reconfigure -backend-config="lock_address=http://terraform-backend.apex-migrations.net/s/ff-demo/" -backend-config="unlock_address=http://terraform-backend.apex-migrations.net/s/ff-demo/" -backend-config="address=http://terraform-backend.apex-migrations.net/s/ff-demo/"
        
      ## Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      ## Run a terraform validate
      - name: Terraform Validate
        id: validate
        # Run even if formatting fails
        if: success() || failure()
        run: terraform validate -no-color

      ## On merge to main apply changes
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

  deploy-container:
    needs: setup-infra
    name: Deploy App Container
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      ## Checkout Github Code #
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker-Compose Remote Deployment  
      - uses: alex-ac/github-action-ssh-docker-compose@master
          with:
            ssh_host: ${{ secrets.HOST }}
            ssh_private_key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
            ssh_user: ${{ secrets.ANSIBLE_SSH_USER }}
            docker_compose_prefix: ff_demo